### ISSUE TITLE
Add authentification

### ISSUE THREAD

**Issue by aitbali** [aitbali/THP2.ZERO#16]
## Why ?

Because we need the users to be authenticated to do certain actions.

## Must have

* [x] A user model \o/
* [x] Auth with: confirmation and login with email or username
  * [x] Confirmation
  * [x] Validation d'email
  * [x] Reset password
* [x] Postman

## Todo

I advise using my [fork](https://github.com/denispasin/devise_token_auth) of devise_auth_token (multiple bug/feature fixes rebased on last stable version). BUT I can understand that you prefer using the normal version of it. If you use my fork, please read the commits to understand how and why I fixed things.

* [x] Add [Devise token auth](https://github.com/lynndylanhurley/devise_token_auth) (or my fork)
* [x] Configure it
* [x] Force users to be auth for accessing to lessons

## Reading list

* https://github.com/denispasin/devise_token_auth
